"use strict";
const $ = (id) => document.getElementById(id); let token = sessionStorage.getItem("aipol:admin") || ""; let actor = sessionStorage.getItem("aipol:actor") || ""; let selected = null;
const otpLabel = document.querySelector('label[for="otp"]');
if (otpLabel) otpLabel.innerHTML = '인증 코드 <span class="muted">(개인 계정만)</span>';
if ($("otp")) $("otp").placeholder = "공동 계정은 비워두세요";
const esc = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function api(path, options={}) { const r=await fetch(path,{...options,headers:{"Content-Type":"application/json","X-Admin-Token":token,...(options.headers||{})}}); let d={};try{d=await r.json()}catch(_){} if(!r.ok)throw new Error(d.detail||"요청 실패");return d; }
function field(id,label,type="text",placeholder="") { return `<label class="field-label" for="${id}">${label}</label><input class="field-input" id="${id}" type="${type}" placeholder="${esc(placeholder)}">`; }
function textarea(id,label,placeholder="") { return `<label class="field-label" for="${id}">${label}</label><textarea class="field-input" id="${id}" rows="5" placeholder="${esc(placeholder)}"></textarea>`; }
function parseObject(id,label){try{const value=JSON.parse($(id).value||"{}");if(!value||Array.isArray(value)||typeof value!=="object")throw new Error();return value;}catch(_){throw new Error(`${label}은 JSON 객체여야 합니다.`);}}
function signedActor(){if(!actor)throw new Error("서명 계정 정보가 없습니다. 로그아웃 후 다시 로그인해 주세요.");return actor;}
function approvedAt(id) { const value=$(id).value;if(!value)throw new Error("실제 승인 일시를 입력해 주세요.");return new Date(value).toISOString(); }
function initForm(){ $("create-fields").innerHTML=field("title","실험 제목")+field("version","실험 버전","text","예: 2026-08-12.1")+field("session","세션 ID")+field("capacity","참가 정원","number")+'<label class="field-label" for="procedure-version">실행 절차</label><select class="field-input" id="procedure-version"><option value="v3" selected>v3 · 최신 11단계</option><option value="v2">v2 · 기존 검토 절차 보존</option><option value="v1">v1 · 기존 운영 절차 보존</option></select>'+field("consent","동의문 버전")+field("consent-text","동의문 본문")+field("question","세 번 동일하게 사용할 주 선택 문항")+field("option-version","정책안 세트 버전")+["A","B","C"].map((id)=>`<fieldset><legend>${id}안 승인 레지스트리</legend>${field(`label-${id}`,"표시명")}${field(`source-${id}`,"출처")}${field(`approver-${id}`,"승인자")}${field(`lever-${id}`,"승인된 레버 값 요약")}</fieldset>`).join(""); }
async function login(){ try{const d=await api("/api/admin/login",{method:"POST",body:JSON.stringify({username:$("user").value,password:$("pw").value,otp:$("otp").value}),headers:{"X-Admin-Token":""}});token=d.token;actor=d.username;sessionStorage.setItem("aipol:admin",token);sessionStorage.setItem("aipol:actor",actor);enter();}catch(e){$("login-error").textContent=e.message;} }
async function enter(){ $("login").classList.add("hidden");$("dashboard").classList.remove("hidden");initForm();initAdminForms();bindTabs();await load(); }
async function load(){ try{const rows=await api("/api/admin/aipol/experiments");$("experiments").innerHTML=rows.length?rows.map((x)=>`<div class="proposal-card"><button class="option-choice experiment-open" data-id="${esc(x.id)}"><span><strong>${esc(x.title)}</strong>${x.collection_enabled?"수집 ON":"수집 OFF"} · ${esc(x.experiment_version)}</span></button>${x.admission_state==="legacy_rotation_required"?`<p class="stage-note"><strong>레거시 참가자격 회전 필요 — 수집 차단</strong></p><button class="rotate-admission" data-rotate-id="${esc(x.id)}" type="button">새 일회용 참가자격 발급</button>`:""}</div>`).join(""):"<p class='muted'>준비된 실험이 없습니다.</p>";document.querySelectorAll(".experiment-open").forEach((b)=>b.onclick=()=>window.openAipolPreparation(rows.find((x)=>x.id===b.dataset.id)));document.querySelectorAll(".rotate-admission").forEach((b)=>b.onclick=()=>rotateLegacyAdmission(b.dataset.rotateId));}catch(e){$("admin-error").textContent=e.message;} }
function downloadAdmissionCsv(experimentId,credentials){const lines=["experiment_id,seat_number,admission_credential",...credentials.map((credential,index)=>`${JSON.stringify(experimentId)},${index+1},${JSON.stringify(credential)}`)];const url=URL.createObjectURL(new Blob(["\uFEFF"+lines.join("\r\n")],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download=`aipol-${experimentId}-admission-credentials.csv`;link.click();URL.revokeObjectURL(url);}
function showAdmissionCredentials(created){const credentials=created.admission_credentials||[];const panel=$("admission-credentials");panel.classList.remove("hidden");panel.innerHTML=`<h3>서버 CSPRNG 일회용 참가 자격 ${credentials.length}개</h3><p class="stage-note"><strong>이 화면에서 한 번만 표시됩니다.</strong> 서버에는 HMAC만 저장되며 목록 API·재로그인·화면 전환 후 원문을 다시 호출할 수 없습니다. 지금 CSV를 안전하게 보관하고 참가자별로 하나씩 배포하세요.</p><button id="download-admission-csv" type="button">CSV 다운로드</button><textarea class="field-input" rows="10" readonly aria-label="일회용 참가 자격">${esc(credentials.join("\n"))}</textarea>`;$("download-admission-csv").onclick=()=>downloadAdmissionCsv(created.id,credentials);}
async function rotateLegacyAdmission(experimentId){const capacityText=prompt("승인된 새 전체 정원을 입력하세요.");if(capacityText===null)return;const new_capacity=Number(capacityText);if(!Number.isInteger(new_capacity)||new_capacity<1){$("admin-error").textContent="새 정원은 1 이상의 정수여야 합니다.";return;}const reason=prompt("레거시 참가자격 회전 사유를 8자 이상 입력하세요.");if(!reason)return;const expected=`ROTATE ${experimentId} TO ${new_capacity}`;const confirmation=prompt(`확인을 위해 다음 문구를 그대로 입력하세요.\n${expected}`);if(confirmation===null)return;try{const rotated=await api(`/api/admin/aipol/experiments/${encodeURIComponent(experimentId)}/admission-seats/rotate`,{method:"POST",body:JSON.stringify({reason,new_capacity,confirmation})});showAdmissionCredentials(rotated);await load();}catch(e){$("admin-error").textContent=e.message;}}
async function create(){ const body={title:$("title").value,experiment_version:$("version").value,session_id:$("session").value,capacity:Number($("capacity").value),procedure_version:$("procedure-version").value,consent_version:$("consent").value,consent_text:$("consent-text").value,question_id:"main-choice",question_text:$("question").value,option_set_version:$("option-version").value,policy_options:["A","B","C"].map((id)=>({policy_option_id:id,label:$(`label-${id}`).value,policy_version:$("option-version").value,source:$(`source-${id}`).value,approved_by:$(`approver-${id}`).value,lever_values:{approved_summary:$(`lever-${id}`).value}}))};try{const created=await api("/api/admin/aipol/experiments",{method:"POST",body:JSON.stringify(body)});const credentials=created.admission_credentials||[];const panel=$("admission-credentials");panel.classList.remove("hidden");panel.innerHTML=`<h3>서버 CSPRNG 일회용 참가 자격 ${credentials.length}개</h3><p class="stage-note"><strong>이 화면에서 한 번만 표시됩니다.</strong> 서버에는 HMAC만 저장되어 목록 API·재로그인·계정 전환 뒤 원문을 다시 노출할 수 없습니다. 지금 CSV를 안전하게 보관하고 참가자별로 하나씩 배포하세요.</p><button id="download-admission-csv" type="button">CSV 다운로드</button><textarea class="field-input" rows="10" readonly aria-label="일회용 참가 자격">${esc(credentials.join("\n"))}</textarea>`;$("download-admission-csv").onclick=()=>downloadAdmissionCsv(created.id,credentials);await load();}catch(e){$("admin-error").textContent=e.message;} }
function initAdminForms(){
  $("source-fields").innerHTML=field("source-id","출처 ID","text","예: kaps")+field("source-name","출처 이름")+field("source-url","기본 HTTPS URL")+field("source-hosts","허용 호스트(쉼표 구분)");
  $("knowledge-fields").innerHTML=field("knowledge-source","출처 ID")+field("knowledge-title","지식 제목")+field("knowledge-url","원문 HTTPS URL")+`<label class="field-label" for="knowledge-text">공개 요약/지식 본문</label><textarea class="field-input" id="knowledge-text" rows="5" maxlength="12000"></textarea>`;
  $("batch-fields").innerHTML=field("batch-id","배치 ID","text","예: overseas-policy")+field("batch-sources","출처 ID(쉼표 구분)")+field("batch-schedule","UTC 일정 또는 manual","text","manual")+field("batch-max","최대 항목","number","100")+`<label><input id="batch-enabled" type="checkbox"> 수동 요청 허용(자동 발행 아님)</label>`;
  $("chatbot-fields").innerHTML=`<label><input id="chat-enabled" type="checkbox"> 공개 챗봇 설정 ON</label><label class="field-label" for="chat-mode-select">생성 모드</label><select id="chat-mode-select" class="field-input"><option value="off">OFF</option><option value="extractive">추출형(비용 없음)</option><option value="azure_foundry">Azure Foundry 관리 ID</option></select><label><input id="chat-fallback" type="checkbox"> Foundry 실패 시 추출형 대체</label>`+field("chat-limit","검색 청크 수","number","4")+field("chat-score","최소 검색 점수","number","0.2")+field("chat-support","최소 주장 지지 점수","number","0.2")+field("chat-budget","월 비용 단위 상한","number","0");
}
function bindTabs(){document.querySelectorAll(".admin-tab").forEach((button)=>button.onclick=async()=>{document.querySelectorAll(".admin-panel").forEach((panel)=>panel.classList.add("hidden"));document.querySelectorAll(".admin-tab").forEach((item)=>item.classList.remove("btn-primary"));$(`tab-${button.dataset.tab}`).classList.remove("hidden");button.classList.add("btn-primary");$("admin-error").textContent="";if(button.dataset.tab==="knowledge")await loadKnowledge();if(button.dataset.tab==="batch")await loadBatch();if(button.dataset.tab==="chatbot")await loadChatbot();});}
async function saveSource(){try{await api("/api/admin/aipol/sources",{method:"POST",body:JSON.stringify({id:$("source-id").value,name:$("source-name").value,base_url:$("source-url").value,allowed_hosts:$("source-hosts").value.split(",").map((x)=>x.trim()).filter(Boolean),enabled:true,public_source:true})});await loadKnowledge();}catch(e){$("admin-error").textContent=e.message;}}
async function saveKnowledge(){try{await api("/api/admin/aipol/knowledge",{method:"POST",body:JSON.stringify({source_id:$("knowledge-source").value,title:$("knowledge-title").value,source_url:$("knowledge-url").value,text:$("knowledge-text").value})});await loadKnowledge();}catch(e){$("admin-error").textContent=e.message;}}
async function knowledgeAction(id,action,revision){try{const reason=action==="revoke"?prompt("철회 사유를 입력하세요."):"";if(action==="revoke"&&!reason)return;await api(`/api/admin/aipol/knowledge/${encodeURIComponent(id)}/${action}`,{method:"POST",body:JSON.stringify({reason:reason||"",expected_revision:Number(revision)})});await loadKnowledge();}catch(e){$("admin-error").textContent=e.message;}}
async function loadKnowledge(){try{const [sources,items]=await Promise.all([api("/api/admin/aipol/sources"),api("/api/admin/aipol/knowledge")]);$("sources").innerHTML=sources.length?`<h3>등록 출처</h3>`+sources.map((x)=>`<p><strong>${esc(x.name)}</strong> · ${esc(x.base_url)} · ${x.public_source?"공개":"비공개"}</p>`).join(""):"<p class='muted'>등록 출처가 없습니다.</p>";$("knowledge").innerHTML=items.length?`<h3>지식 개정본</h3>`+items.map((x)=>`<article class="proposal-card"><strong>${esc(x.title)}</strong><p>${esc(x.text)}</p><p class="artifact-meta">${esc(x.state)} · r${x.revision} · ${esc(x.source_url)}</p><div class="action-row">${x.state==="draft"?`<button data-kb="${esc(x.id)}" data-revision="${x.revision}" data-action="submit">검토 요청</button>`:""}${x.state==="in_review"?`<button data-kb="${esc(x.id)}" data-revision="${x.revision}" data-action="approve" class="btn-primary">별도 계정 승인</button>`:""}${x.state==="approved"?`<button data-kb="${esc(x.id)}" data-revision="${x.revision}" data-action="revoke">승인 철회</button>`:""}</div></article>`).join(""):"<p class='muted'>지식이 없습니다.</p>";document.querySelectorAll("[data-kb]").forEach((button)=>button.onclick=()=>knowledgeAction(button.dataset.kb,button.dataset.action,button.dataset.revision));}catch(e){$("admin-error").textContent=e.message;}}
async function saveBatch(){try{await api(`/api/admin/aipol/batch-configs/${encodeURIComponent($("batch-id").value)}`,{method:"PUT",body:JSON.stringify({source_ids:$("batch-sources").value.split(",").map((x)=>x.trim()).filter(Boolean),schedule_utc:$("batch-schedule").value||"manual",maximum_items:Number($("batch-max").value||100),enabled:$("batch-enabled").checked})});await loadBatch();}catch(e){$("admin-error").textContent=e.message;}}
async function requestBatch(id){try{await api(`/api/admin/aipol/batch-configs/${encodeURIComponent(id)}/request`,{method:"POST"});await loadBatch();}catch(e){$("admin-error").textContent=e.message;}}
async function refreshBatch(id){try{await api(`/api/admin/aipol/batch-runs/${encodeURIComponent(id)}/status`);await loadBatch();}catch(e){$("admin-error").textContent=e.message;}}
async function loadBatch(){try{const [configs,runs]=await Promise.all([api("/api/admin/aipol/batch-configs"),api("/api/admin/aipol/batch-runs")]);$("batch-configs").innerHTML=configs.length?configs.map((x)=>`<p><strong>${esc(x.id)}</strong> · ${x.enabled?"요청 ON":"OFF"} · 최대 ${x.maximum_items} <button data-batch="${esc(x.id)}" ${x.enabled?"":"disabled"}>수동 요청</button></p>`).join(""):"<p class='muted'>배치 설정이 없습니다.</p>";$("batch-runs").innerHTML=runs.length?runs.map((x)=>`<p>${esc(x.id)} · ${esc(x.status)} · ${esc(x.requested_by)} ${["processing","running","started"].includes(x.status)?`<button data-refresh-batch="${esc(x.id)}">상태 새로고침</button>`:""}</p>`).join(""):"<p class='muted'>실행 요청이 없습니다.</p>";document.querySelectorAll("[data-batch]").forEach((button)=>button.onclick=()=>requestBatch(button.dataset.batch));document.querySelectorAll("[data-refresh-batch]").forEach((button)=>button.onclick=()=>refreshBatch(button.dataset.refreshBatch));}catch(e){$("admin-error").textContent=e.message;}}
async function loadChatbot(){try{const x=await api("/api/admin/aipol/chatbot-config");$("chat-enabled").checked=x.enabled;$("chat-mode-select").value=x.generator_mode;$("chat-fallback").checked=x.allow_extractive_fallback;$("chat-limit").value=x.retrieval_limit;$("chat-score").value=x.minimum_score;$("chat-support").value=x.minimum_claim_support;$("chat-budget").value=x.monthly_budget_units;}catch(e){$("admin-error").textContent=e.message;}}
async function saveChatbot(){try{await api("/api/admin/aipol/chatbot-config",{method:"PUT",body:JSON.stringify({enabled:$("chat-enabled").checked,generator_mode:$("chat-mode-select").value,allow_extractive_fallback:$("chat-fallback").checked,retrieval_limit:Number($("chat-limit").value),minimum_score:Number($("chat-score").value),minimum_claim_support:Number($("chat-support").value),monthly_budget_units:Number($("chat-budget").value)})});await loadChatbot();}catch(e){$("admin-error").textContent=e.message;}}
$("login-btn").onclick=login;$("create").onclick=create;$("save-source").onclick=saveSource;$("save-knowledge").onclick=saveKnowledge;$("save-batch").onclick=saveBatch;$("save-chatbot").onclick=saveChatbot;$("pw").onkeydown=(e)=>{if(e.key==="Enter")login();};if(token)enter();
